import type { JourneyMapProject } from '../types';

// This is the first project config that can seed a future multi-tenant builder.
// The current app still reads hardcoded component data, but this file establishes
// the long-term source-of-truth shape we can migrate the renderer onto next.
export const asuNondegreeProject: JourneyMapProject = {
  organization: {
    id: 'asu',
    slug: 'asu',
    name: 'Arizona State University',
  },
  map: {
    id: 'nondegree-discovery',
    slug: 'nondegree-discovery',
    title: 'Nondegree Journey Map',
    brand: {
      title: 'Nondegree Journey Map',
      logoAsset: 'asu-logo',
      faviconAsset: 'JourneyMap-Favicon.png',
      pageBackground: '#FAFAFA',
    },
    theme: {
      pageBackground: '#FAFAFA',
      panelBackground: '#FFFFFF',
      pathStrokeWidth: 42,
      centerlineStrokeWidth: 3,
      stageColors: ['#78BE20', '#00A3E0', '#FF7F32', '#E74973', '#FFC627'],
    },
    stateLabels: {
      current: 'Current state',
      future: 'Future state',
    },
    publishing: {
      siteSlug: 'asu-nondegree-discovery',
    },
    features: {
      currentStateEnabled: true,
      futureStateEnabled: true,
      comparisonModalEnabled: true,
      guidedTourEnabled: true,
    },
    stages: [
      {
        id: 'research',
        number: '01',
        title: 'Research',
        color: '#78BE20',
        description: 'Students explore non-degree pathways and evaluate options.',
        currentSummary:
          'Prospective students find non-degree options via Google, admissions site, or course search. They browse and decide whether to start with a class or the application.',
        futureSummary:
          'Students discover non-degree options through consistent, well-connected pathways with clear policies and direct links from class search to the application.',
      },
      {
        id: 'apply',
        number: '02',
        title: 'Apply',
        color: '#00A3E0',
        description: 'Students sign in, start, and submit their application.',
        currentSummary:
          'Students create accounts, navigate branching questions, complete biographical and academic history sections, and submit applications with payment.',
        futureSummary:
          'A single, unified application guides students through only essential questions with clear next steps and the ability to reserve a class seat upfront.',
      },
      {
        id: 'decision',
        number: '03',
        title: 'Decision',
        color: '#FF7F32',
        description: 'Students track status and receive an admission decision.',
        currentSummary:
          'Students await system review and propagation, receive admit emails, and become registration eligible — often with no clear timeline or next steps.',
        futureSummary:
          'Students receive timely communications with predictable timelines and clear next steps, reducing anxiety and uncertainty during the waiting period.',
      },
      {
        id: 'register',
        number: '04',
        title: 'Register',
        color: '#E74973',
        description: 'Students complete enrollment and register for their class.',
        currentSummary:
          'Students search and add courses, navigate eligibility confusion and seat availability uncertainty, then click through to register or enroll.',
        futureSummary:
          'Students sign into MyASU with a clear priority task, find their course, and register seamlessly without eligibility confusion or dead ends.',
      },
      {
        id: 'tuition',
        number: '05',
        title: 'Tuition',
        color: '#FFC627',
        description: 'Students understand payment timing and tuition costs.',
        currentSummary:
          'Students navigate to the Finances tab in MyASU and pay tuition — often with confusion about amounts, timing, and payment options.',
        futureSummary:
          'Students see clear cost breakdowns upfront in MyASU with transparent payment options and no confusion about amounts or timing.',
      },
    ],
    currentSummaries: [
      {
        number: '01',
        name: 'Research',
        color: '#78BE20',
        description:
          'Prospective students find non-degree options via Google, admissions site, or course search. They browse and decide whether to start with a class or the application.',
      },
      {
        number: '02',
        name: 'Apply',
        color: '#00A3E0',
        description:
          'Students create accounts, navigate branching questions, complete biographical and academic history sections, and submit applications with payment.',
      },
      {
        number: '03',
        name: 'Decision',
        color: '#FF7F32',
        description:
          'Students await system review and propagation, receive admit emails, and become registration eligible — often with no clear timeline or next steps.',
      },
      {
        number: '04',
        name: 'Register',
        color: '#E74973',
        description:
          'Students search and add courses, navigate eligibility confusion and seat availability uncertainty, then click through to register or enroll.',
      },
      {
        number: '05',
        name: 'Tuition',
        color: '#FFC627',
        description:
          'Students navigate to the Finances tab in MyASU and pay tuition — often with confusion about amounts, timing, and payment options.',
      },
    ],
    futureSummaries: [
      {
        number: '01',
        name: 'Research',
        color: '#78BE20',
        description:
          'Students discover non-degree options through consistent, well-connected pathways with clear policies and direct links from class search to the application.',
      },
      {
        number: '02',
        name: 'Apply',
        color: '#00A3E0',
        description:
          'A single, unified application guides students through only essential questions with clear next steps and the ability to reserve a class seat upfront.',
      },
      {
        number: '03',
        name: 'Decision',
        color: '#FF7F32',
        description:
          'Students receive timely communications with predictable timelines and clear next steps, reducing anxiety and uncertainty during the waiting period.',
      },
      {
        number: '04',
        name: 'Register',
        color: '#E74973',
        description:
          'Students sign into MyASU with a clear priority task, find their course, and register seamlessly without eligibility confusion or dead ends.',
      },
      {
        number: '05',
        name: 'Tuition',
        color: '#FFC627',
        description:
          'Students see clear cost breakdowns upfront in MyASU with transparent payment options and no confusion about amounts or timing.',
      },
    ],
    currentStateMarkers: [
      {
        id: 'current-1',
        label: 'No direct\u00a0path from\nClass\u00a0Search to application',
        labelVariant: 'plain',
        desktop: { pct: 0.22, side: 'above' },
        mobile: { pct: 0.22, side: 'above' },
      },
      {
        id: 'current-2',
        label: 'Landing\u00a0pages with\npolicy\u00a0contradictions',
        labelVariant: 'plain',
        desktop: { pct: 0.27, side: 'below' },
        mobile: { pct: 0.25, side: 'right' },
      },
      {
        id: 'current-3',
        label: 'Two\u00a0applications\ncreates\nconfusion',
        labelVariant: 'plain',
        desktop: { pct: 0.35, side: 'left' },
        mobile: { pct: 0.32, side: 'above' },
      },
      {
        id: 'current-4',
        label: 'Non-essential\u00a0questions\nin\nthe app',
        labelVariant: 'plain',
        desktop: { pct: 0.43, side: 'right' },
        mobile: { pct: 0.46, side: 'above' },
      },
      {
        id: 'current-5',
        label: 'Cannot\u00a0reserve a seat\nbefore\u00a0registering',
        labelVariant: 'plain',
        desktop: { pct: 0.475, side: 'left' },
        mobile: { pct: 0.49, side: 'above' },
      },
      {
        id: 'current-6',
        label: '"Pay\u00a0later" option\ncreates confusion\nand delays',
        labelVariant: 'plain',
        desktop: { pct: 0.52, side: 'left' },
        mobile: { pct: 0.53, side: 'above' },
      },
      {
        id: 'current-7',
        label: 'Unpredictable\u00a0admission\ntimeline',
        labelVariant: 'plain',
        desktop: { pct: 0.64, side: 'right' },
        mobile: { pct: 0.64, side: 'above' },
      },
      {
        id: 'current-8',
        label: 'Class\u00a0could\u00a0fill\u00a0up\nwhile\u00a0waiting',
        labelVariant: 'plain',
        desktop: { pct: 0.67, side: 'right' },
        mobile: { pct: 0.68, side: 'above' },
      },
      {
        id: 'current-9',
        label: 'Able\u00a0to\u00a0add\u00a0courses\nnot\u00a0eligible\u00a0to\u00a0enroll\u00a0in',
        labelVariant: 'plain',
        desktop: { pct: 0.74, side: 'above' },
        mobile: { pct: 0.74, side: 'left' },
      },
      {
        id: 'current-10',
        label: 'Unclear\u00a0how\u00a0much\nthe\u00a0class\u00a0will\u00a0cost',
        labelVariant: 'plain',
        desktop: { pct: 0.8, side: 'below' },
        mobile: { pct: 0.78, side: 'left' },
      },
    ],
    futureStateMarkers: [
      {
        id: 'future-1',
        stageId: 'research',
        label: 'Consistent policies\non landing pages',
        modalTitle: 'Consistent policies on landing pages',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.22, side: 'above' },
        mobile: { pct: 0.22, side: 'right' },
        mobileLabel: { side: 'right', distance: 30, maxWidth: 230, shiftY: -6 },
        beforeImage: 'step-01-landing-pages-before.jpg',
        afterImage: 'step-01-landing-pages-after.jpg',
      },
      {
        id: 'future-2',
        stageId: 'research',
        label: 'Finds a class to\nenroll in',
        modalTitle: 'Finds a class to enroll in',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.255, side: 'below' },
        mobile: { pct: 0.235, side: 'right' },
        mobileLabel: { side: 'right', distance: 30, maxWidth: 240, shiftY: 2 },
        beforeImage: 'step-02-class-search-link-before.jpg',
        afterImage: 'step-02-class-search-link-after.jpg',
      },
      {
        id: 'future-3',
        stageId: 'apply',
        label: 'Signs in\nto apply',
        modalTitle: 'Signs in to apply',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.31, side: 'left' },
        mobile: { pct: 0.285, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 200 },
        beforeImage: 'step-03-signin-to-continue-before.jpg',
        afterImage: 'step-03-signin-to-continue-after.jpg',
      },
      {
        id: 'future-4',
        stageId: 'apply',
        label: 'Starts\napplication',
        modalTitle: 'Starts application',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.34, side: 'left' },
        mobile: { pct: 0.315, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 200, shiftX: 6 },
        beforeImage: 'step-04-unified-application-before.jpg',
        afterImage: 'step-04-unified-application-after.jpg',
      },
      {
        id: 'future-5',
        stageId: 'apply',
        label: 'App\u00a0started\nemail',
        modalTitle: 'App started email',
        icon: 'email',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.45, side: 'left' },
        mobile: { pct: 0.35, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 220, shiftX: -10 },
        beforeImage: 'step-05-next-steps-comms-before.jpg',
        afterImage: 'step-05-next-steps-comms-after.jpg',
      },
      {
        id: 'future-6',
        stageId: 'apply',
        label: 'Confirms\nclass',
        modalTitle: 'Confirms class',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.48, side: 'left' },
        mobile: { pct: 0.4575, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 180, shiftX: 8 },
        beforeImage: 'step-06-applies-for-class-before.jpg',
        afterImage: 'step-06-applies-for-class-after.jpg',
      },
      {
        id: 'future-7',
        stageId: 'apply',
        label: 'Submits app\nand pays fee',
        modalTitle: 'Submits app and pays fee',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.52, side: 'left' },
        mobile: { pct: 0.49, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 220, shiftX: 12 },
        beforeImage: 'step-07-submits-app-before.jpg',
        afterImage: 'step-07-submits-app-after.jpg',
      },
      {
        id: 'future-8',
        stageId: 'apply',
        label: 'App submitted\nemail',
        modalTitle: 'App submitted email',
        icon: 'email',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.63, side: 'right' },
        mobile: { pct: 0.52, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 180, shiftX: -8 },
        beforeImage: 'step-08-next-steps-comms-before.jpg',
        afterImage: 'step-08-next-steps-comms-after.jpg',
      },
      {
        id: 'future-9',
        stageId: 'decision',
        label: 'Tracks application\nstatus',
        modalTitle: 'Tracks application status',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.655, side: 'right' },
        mobile: { pct: 0.64, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 220, shiftX: 12 },
        beforeImage: 'step-09-track-application-status-before.jpg',
        afterImage: 'step-09-track-application-status-after.jpg',
      },
      {
        id: 'future-10',
        stageId: 'decision',
        label: 'Admission\u00a0decision\nemail',
        modalTitle: 'Admission decision email',
        icon: 'email',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.68, side: 'left' },
        mobile: { pct: 0.7, side: 'above' },
        mobileLabel: { side: 'above', distance: 30, maxWidth: 320, shiftX: -20 },
        beforeImage: 'step-10-admission-dec-comms-before.jpg',
        afterImage: 'step-10-admission-dec-comms-after.jpg',
      },
      {
        id: 'future-11',
        stageId: 'register',
        label: 'Completes\u00a0enrollment\nin class',
        modalTitle: 'Completes enrollment in class',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.715, side: 'above' },
        mobile: { pct: 0.73, side: 'left' },
        mobileLabel: { side: 'left', distance: 30, maxWidth: 320 },
        beforeImage: 'step-11-seamless-registration-before.jpg',
        afterImage: 'step-11-seamless-registration-after.jpg',
      },
      {
        id: 'future-12',
        stageId: 'tuition',
        label: 'Payment\u00a0reminder\nemail',
        modalTitle: 'Payment reminder email',
        icon: 'email',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.75, side: 'below' },
        mobile: { pct: 0.76, side: 'left' },
        mobileLabel: { side: 'left', distance: 30, maxWidth: 320 },
        beforeImage: 'step-12-payment-reminder-comms-before.jpg',
        afterImage: 'step-12-payment-reminder-comms-after.jpg',
      },
      {
        id: 'future-13',
        stageId: 'tuition',
        label: 'Pays tuition',
        modalTitle: 'Pays tuition',
        labelVariant: 'interactive-card',
        desktop: { pct: 0.79, side: 'above' },
        mobile: { pct: 0.79, side: 'left' },
        mobileLabel: { side: 'left', distance: 30, maxWidth: 180 },
        beforeImage: 'step-13-tuition-payment-before.jpg',
        afterImage: 'step-13-tuition-payment-after.jpg',
      },
    ],
    guidedTour: {
      enabled: true,
      title: 'This map is interactive',
      body: 'Each dot marks a moment in the student experience. Click to see current friction and the proposed improvement side by side.',
      desktopAnchorMarkerId: 'future-2',
      mobileAnchorMarkerId: 'future-1',
    },
  },
};
